#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-File-MMagic
Version  : 1.16
Release  : 1
URL      : http://search.cpan.org/CPAN/authors/id/K/KN/KNOK/File-MMagic-1.16.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/K/KN/KNOK/File-MMagic-1.16.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause-Attribution
Requires: perl-File-MMagic-doc
BuildRequires : file-dev

%description
File::MMagic
1. はじめに
このモジュールは、file(1)コマンドに相当する機能、すなわちファイルの内
容からその種類を推測するためのものです。

%package doc
Summary: doc components for the perl-File-MMagic package.
Group: Documentation

%description doc
doc components for the perl-File-MMagic package.


%prep
%setup -q -n File-MMagic-1.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test || :

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/File/MMagic.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
